spring:
  datasource:
    druid:
      url: ${mycloud.db.url}
      username: ${mycloud.db.username}
      password: ${mycloud.db.password}
      #初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 8
      #获取连接等待超时的时间
      max-wait: 60000
      validation-query-timeout: 28000
      test-while-idle: true
      validation-query: SELECT'x'
      #使用sqlite要注释掉，不然会报
      #java.lang.IllegalStateException: dbType not support : sqlite, url jdbc:sqlite:
      #      filters: stat,wall,slf4j
      test-on-borrow: false
      pool-prepared-statements: false
      test-on-return: false
      #间隔多久检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 28000
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
      #        有security的jwt就不需要设账号密码了
      #        login-username:
      #        login-password:
      #        allow:
      #        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'

  jackson:
    serialization:
      #json返回时间戳
      write-dates-as-timestamps: true

#  cache:
#    type: CAFFEINE

  redis:
    database: ${mycloud.redis.database}
    host: ${mycloud.redis.host}
    port: ${mycloud.redis.port}
    password: ${mycloud.redis.password}
    timeout: ${mycloud.redis.timeout}
    jedis:
      pool:
        max-wait: 10s
        min-idle: 0
        max-idle: 8
        max-active: 8

mycloud:
  webUploadMaxFileSize: ${MYCLOUD_WEB_UPLOAD_MAX_FILE_SIZE:1024MB}
  webUploadMaxRequestSize: ${MYCLOUD_WEB_UPLOAD_MAX_REQUEST_SIZE:1024MB}

  mycloudPath: ${MYCLOUD_PATH:./}
  localFileMaxSpaceRate: ${MYCLOUD_LOCAL_FILE_MAX_SPACE_RATE:0.8}
  downloadUrlConnectTimeout: ${MYCLOUD_DOWBLOAD_UTL_CONNECT_TIMEOUT:5000} #五秒
  maxTmpFileSaveTime: ${MYCLOUD_MAX_TMP_FILE_SAVE_TIME:864000000} #十天
  domain: ${MYCLOUD_DOMAIN:}
  secret: ${MYCLOUD_SECRET:${random.value}}

  db:
    type: sqlite
    url: ${mycloud.db.${mycloud.db.type}}
    mysql: jdbc:mysql://${mycloud.db.host}:${mycloud.db.port}/${mycloud.db.name}?useUnicode=true&characterEncoding=UTF8&useSSL=false
    sqlite: jdbc:sqlite:${mycloud.mycloudPath}/mycloud.db
    host: ${MYCLOUD_DB_HOST:127.0.0.1}
    port: ${MYCLOUD_DB_PORT:3306}
    name: ${MYCLOUD_DB_NAME:mycloud}
    username: ${MYCLOUD_DB_USERNAME:root}
    password: ${MYCLOUD_DB_PASSWORD:root}

  redis:
    enable: ${MYCLOUD_REDIS_ENABLE:false}
    database: ${MYCLOUD_REDIS_DATABASE:0}
    host: ${MYCLOUD_REDIS_HOST:127.0.0.1}
    port: ${MYCLOUD_REDIS_PORT:6379}
    password: ${MYCLOUD_REDIS_PASSWORD:root}
    timeout: ${MYCLOUD_REDIS_TIMEOUT:10s}

  hdfsUrl: ${MYCLOUD_HDFS_URL:}


logging:
  level:
    top:
      cellargalaxy:
        mycloud:
          dao:
            '*': DEBUG
          controller:
            security:
              '*': DEBUG
          service:
            schedule:
              '*': DEBUG