spring:
  datasource:
    druid:
      url: jdbc:mysql://${mycloud.dbHost}:${mycloud.dbPort}/${mycloud.dbName}?useUnicode=true&characterEncoding=UTF8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: ${mycloud.dbUsername}
      password: ${mycloud.dbPassword}
#      初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 5
#      获取连接等待超时的时间
      max-wait: 60000
      validation-query-timeout: 28000
      test-while-idle: true
      validation-query: SELECT'x'
      filters: stat,wall,slf4j
      test-on-borrow: false
      pool-prepared-statements: false
      test-on-return: false
#      间隔多久检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 28000
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
#        有security的jwt就不需要设账号密码了
#        login-username:
#        login-password:
#        allow:
#        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'

  jackson:
    serialization:
#      json返回时间戳
      write-dates-as-timestamps: true

  cache:
    type: CAFFEINE

  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

mycloud:
  webUploadMaxFileSize: ${MYCLOUD_WEB_UPLOAD_MAX_FILE_SIZE:1024MB}
  webUploadMaxRequestSize: ${MYCLOUD_WEB_UPLOAD_MAX_REQUEST_SIZE:1024MB}

  mycloudPath: ${MYCLOUD_PATH:./}
  localFileMaxSpaceRate: ${MYCLOUD_LOCAL_FILE_MAX_SPACE_RATE:0.8}
  domain: ${MYCLOUD_DOMAIN:}
  secret: ${MYCLOUD_SECRET:${random.value}}

  mycloudUsername: ${MYCLOUD_USERNAME:mycloud}
  mycloudPassword: ${MYCLOUD_PASSWORD:mycloud}

  dbHost: ${MYCLOUD_DB_HOST}
  dbPort: ${MYCLOUD_DB_PORT:3306}
  dbName: ${MYCLOUD_DB_NAME:mycloud}
  dbUsername: ${MYCLOUD_DB_USERNAME:root}
  dbPassword: ${MYCLOUD_DB_PASSWORD}

  hdfsUrl: ${MYCLOUD_HDFS_URL:}


logging:
  level:
    top:
      cellargalaxy:
        mycloud:
          dao:
            '*': DEBUG
          controller:
            security:
              '*': DEBUG

#MYCLOUD_MYSQL_DATABASE_NAME:mycloud
#MYCLOUD_MYSQL_USERNAME:root
#MYCLOUD_WEB_UPLOAD_MAX_FILE_SIZE:1024MB
#MYCLOUD_WEB_UPLOAD_MAX_REQUEST_SIZE:1024MB
#MYCLOUD_LOCAL_FILE_MAX_SPACE_RATE:0.8
#MYCLOUD_INSTALLATION_TYPE:local
#MYCLOUD_PATH:./
#MYCLOUD_SECRET:${random.value}
#MYCLOUD_DOMAIN:
#MYCLOUD_MYSQL_IP_PORT
#MYCLOUD_MYSQL_PASSWORD