version: '2'
services:
  mycloud:
    image: frolvlad/alpine-oraclejdk8:slim
    container_name: mycloud
    restart: always
    environment:
      MYCLOUD_DOMAIN: http://drive.cellargalaxy.top
      MYCLOUD_SECRET: MYCLOUD_SECRET

      MYCLOUD_DB_TYPE: sqlite

      MYCLOUD_MYSQL_HOST: 127.0.0.1
      MYCLOUD_MYSQL_PORT: 3306
      MYCLOUD_MYSQL_NAME: mycloud
      MYCLOUD_MYSQL_USERNAME: root
      MYCLOUD_MYSQL_PASSWORD: root

      MYCLOUD_REDIS_ENABLE: 'false'
      MYCLOUD_REDIS_DATABASE: 0
      MYCLOUD_REDIS_HOST: 127.0.0.1
      MYCLOUD_REDIS_PORT: 6379
      MYCLOUD_REDIS_PASSWORD: root
      MYCLOUD_REDIS_TIMEOUT: 10s

      MYCLOUD_WEB_UPLOAD_MAX_FILE_SIZE: 1024MB
      MYCLOUD_WEB_UPLOAD_MAX_REQUEST_SIZE: 1024MB
      MYCLOUD_LOCAL_FILE_MAX_SPACE_RATE: 0.8
      MYCLOUD_MAX_TMP_FILE_SAVE_TIME: 864000000 #十天
      MYCLOUD_MAX_TMP_FILE_SIZE: 10485760 #10MB
      MYCLOUD_DOWBLOAD_UTL_CONNECT_TIMEOUT: 5000 #五秒
      MYCLOUD_PATH: /root/mycloud
    volumes:
      - ./mycloud.jar:/root/mycloud.jar
      - mycloud:/root/mycloud
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command: java -jar /root/mycloud.jar
    ports:
      - 18088:8080

volumes:
  mycloud: