version: '2'
services:
  mycloud:
    image: frolvlad/alpine-oraclejdk8:slim
    container_name: mycloud
    restart: always
    environment:
      MYCLOUD_DB_HOST: 10.0.2.15
      MYCLOUD_DB_HOST: 3306
      MYCLOUD_DB_NAME: mycloud
      MYCLOUD_DB_USERNAME: root
      MYCLOUD_DB_PASSWORD: mysqlpw123

      MYCLOUD_USERNAME: mycloud
      MYCLOUD_PASSWORD: mycloud

      MYCLOUD_DOMAIN: http://drive.cellargalaxy.top
      MYCLOUD_SECRET: MYCLOUD_SECRET

      MYCLOUD_WEB_UPLOAD_MAX_FILE_SIZE: 1024MB
      MYCLOUD_WEB_UPLOAD_MAX_REQUEST_SIZE: 1024MB
      MYCLOUD_LOCAL_FILE_MAX_SPACE_RATE: 0.8
      MYCLOUD_PATH: /root
    volumes:
      - ./mycloud.jar:/root/mycloud.jar
      - ./application.yml:/root/application.yml
      - mycloud:/root/mycloud
    command: java -jar /root/mycloud.jar
    ports:
      - 18088:8080

volumes:
  mycloud: